AWSTemplateFormatVersion: '2010-09-09'
Description: Sample IAM Role for EC2

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DeepikaEC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess